/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    About: typeof import('./src/components/About/index.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CodeEditor: typeof import('./src/components/CodeEditor/index.vue')['default']
    ComfyuiPlayground: typeof import('./src/components/ComfyuiPlayground/index.vue')['default']
    ComfyuiWorkflowEditor: typeof import('./src/components/ComfyuiWorkflowEditor/index.vue')['default']
    Config: typeof import('./src/components/Config/index.vue')['default']
    HistoryModal: typeof import('./src/components/HistoryModal/index.vue')['default']
    ParamsManager: typeof import('./src/components/ParamsManager/index.vue')['default']
    PostImage: typeof import('./src/components/PostImage/index.vue')['default']
    Preview: typeof import('./src/components/preview/index.vue')['default']
    PreviewActions: typeof import('./src/components/preview/components/preview-actions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveTemplateDialog: typeof import('./src/components/preview/components/save-template-dialog.vue')['default']
    TemplatesListDialog: typeof import('./src/components/preview/components/templates-list-dialog.vue')['default']
    ThemeDemo: typeof import('./src/components/ThemeDemo/index.vue')['default']
    UpdateModal: typeof import('./src/components/About/UpdateModal.vue')['default']
  }
}
